// Copyright (c) 2010-2014 SharpDX - Alexandre Mutel
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

using System;
using System.Runtime.InteropServices;

namespace SharpDX.DirectInput
{
    /// <summary>
    /// This class describes a Periodic force effect. 
    /// It is passed in the <see cref="EffectParameters.Parameters"/> of the <see cref="EffectParameters"/> structure.
    /// </summary>
    public class PeriodicForce : TypeSpecificParameters
    {
        /// <summary>
        /// Gets or sets the magnitude.
        /// Magnitude of the effect, in the range from 0 through 10,000. If an envelope is applied to this effect, the value represents the magnitude of the sustain. If no envelope is applied, the value represents the amplitude of the entire effect. 
        /// </summary>
        /// <value>The magnitude.</value>
        public int Magnitude { get; set; }

        /// <summary>
        /// Gets or sets the offset of the effect.
        /// The range of forces generated by the effect is lOffset minus dwMagnitude to lOffset plus dwMagnitude. The value of the lOffset member is also the baseline for any envelope that is applied to the effect.
        /// </summary>
        /// <value>The offset.</value>
        public int Offset { get; set; }

        /// <summary>
        /// Gets or sets the phase.
        /// Position in the cycle of the periodic effect at which playback begins, in the range from 0 through 35,999. A device driver cannot provide support for all values in the dwPhase member. In this case, the value is rounded off to the nearest supported value. 
        /// </summary>
        /// <value>The phase.</value>
        public int Phase { get; set; }

        /// <summary>
        /// Gets or sets the period of the effect, in microseconds. 
        /// </summary>
        /// <value>The period.</value>
        public int Period { get; set; }

        /// <summary>
        /// Marshal this class from an unmanaged buffer.
        /// </summary>
        /// <param name="bufferSize">The size of the unmanaged buffer.</param>
        /// <param name="bufferPointer">The pointer to the unmanaged buffer.</param>
        /// <returns>An instance of TypeSpecificParameters or null</returns>
        protected override TypeSpecificParameters MarshalFrom(int bufferSize, IntPtr bufferPointer)
        {
            unsafe
            {
                if (bufferSize != sizeof(RawPeriodicForce))
                    return null;

                Magnitude = ((RawPeriodicForce*)bufferPointer)->Magnitude;
                Offset = ((RawPeriodicForce*)bufferPointer)->Offset;
                Phase = ((RawPeriodicForce*)bufferPointer)->Phase;
                Period = ((RawPeriodicForce*)bufferPointer)->Period;
                return this;
            }
        }

        /// <summary>
        /// Marshals this class to its native/unmanaged counterpart.
        /// </summary>
        /// <returns>A pointer to an allocated buffer containing the unmanaged structure.</returns>
        internal override IntPtr MarshalTo()
        {
            unsafe
            {
                var pData = Marshal.AllocHGlobal(Size);
                ((RawPeriodicForce*)pData)->Magnitude = Magnitude;
                ((RawPeriodicForce*)pData)->Offset = Offset;
                ((RawPeriodicForce*)pData)->Phase = Phase;
                ((RawPeriodicForce*)pData)->Period = Period;
                return pData;
            }
        }

        /// <summary>
        /// Gets the size of this specific parameter.
        /// </summary>
        /// <value>The size.</value>
        public override int Size
        {
            get { return Utilities.SizeOf<RawPeriodicForce>(); }
        }
    }
}