// Copyright (c) 2010-2014 SharpDX - Alexandre Mutel
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

//------------------------------------------------------------------------------
// <auto-generated>
//     Types declaration for SharpDX.RawInput namespace.
//     This code was generated by a tool.
//     Date : 04/04/2015 23:02:53
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Collections.Generic;
namespace SharpDX.XAudio2
{
#pragma warning disable 649
#pragma warning disable 419
#pragma warning disable 1587
#pragma warning disable 1574

    internal partial class LocalInterop
    {
        public static unsafe int CalliGetDeviceDetails(void* thisObject,int arg0, void* arg1,void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int CalliInitialize(void* thisObject,int arg0, int arg1,void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int CalliCreateMasteringVoice(void* thisObject, void* arg0, int arg1, int arg2, int arg3, int arg4, void* arg5, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int CalliGetDeviceCount(void* thisObject, void* arg0, void* methodPtr) {throw new NotImplementedException(); }
    }
}
