// Copyright (c) 2010-2014 SharpDX - Alexandre Mutel
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

//------------------------------------------------------------------------------
// <auto-generated>
//     Types declaration for SharpDX.RawInput namespace.
//     This code was generated by a tool.
//     Date : 6/17/2016 5:56:17 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Collections.Generic;
#if DESKTOP_APP
namespace SharpDX.MediaFoundation
{
#pragma warning disable 649
#pragma warning disable 419
#pragma warning disable 1587
#pragma warning disable 1574

    internal partial class LocalInterop
    {
        public static unsafe int Calliint(void* thisObject, void* arg0, void* arg1, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, void* arg0, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, int arg0, void* arg1, void* methodPtr) { throw new NotImplementedException(); }
        // public static unsafe int Calliint3(void* thisObject, SharpDX.Color4 arg0, void* methodPtr) { throw new NotImplementedException(); }
        // public static unsafe int Calliint(void* thisObject, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint5(void* thisObject, SharpDX.Mathematics.Interop.RawBool arg0, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, int arg0, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, int arg0, int arg1, void* methodPtr) { throw new NotImplementedException(); }
        //  public static unsafe int Calliint(void* thisObject, long arg0, long arg1, void* methodPtr) { throw new NotImplementedException(); }
        //  public static unsafe int Calliint(void* thisObject, long arg0, void* methodPtr) { throw new NotImplementedException(); }
        //  public static unsafe int Calliint(void* thisObject, long arg0, float arg1, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, void* arg0, void* arg1, void* arg2, void* arg3, void* methodPtr) { throw new NotImplementedException(); }
        //   public static unsafe void Callivoid(void* thisObject, long arg0, long arg1, void* methodPtr) { throw new NotImplementedException(); }
        //   public static unsafe void Callivoid(void* thisObject, void* methodPtr) { throw new NotImplementedException(); }
        //     public static unsafe int Calliint(void* thisObject, float arg0, float arg1, int arg2, int arg3, void* arg4, void* arg5, void* methodPtr) { throw new NotImplementedException(); }
        //    public static unsafe int Calliint(void* thisObject, int arg0, int arg1, void* arg2, void* arg3, void* arg4, void* arg5, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint16(void* thisObject, void* arg0, SharpDX.Mathematics.Interop.RawBool arg1, void* methodPtr) { throw new NotImplementedException(); }
        //  public static unsafe void Callivoid(void* thisObject, void* arg0, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint18(void* thisObject, int arg0, SharpDX.Mathematics.Interop.RawBool arg1, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, int arg0, void* arg1, void* arg2, void* methodPtr) { throw new NotImplementedException(); }
        //    public static unsafe int Calliint(void* thisObject, float arg0, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint21(void* thisObject, SharpDX.Mathematics.Interop.RawBool arg0, void* arg1, void* arg2, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint22(void* thisObject, void* arg0, SharpDX.Mathematics.Interop.RawBool arg1, void* arg2, void* arg3, void* methodPtr) { throw new NotImplementedException(); }
        //    public static unsafe int Calliint(void* thisObject, int arg0, short arg1, void* methodPtr) { throw new NotImplementedException(); }
        //    public static unsafe int Calliint(void* thisObject, short arg0, short arg1, void* methodPtr) { throw new NotImplementedException(); }
        //    public static unsafe int Calliint(void* thisObject, void* arg0, int arg1, void* arg2, void* arg3, void* arg4, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, short arg0, void* arg1, long arg2, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, short arg0, void* arg1, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, void* arg0, long arg1, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, void* arg0, int arg1, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint30(void* thisObject, void* arg0, int arg1, SharpDX.Mathematics.Interop.RawBool arg2, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, void* arg0, void* arg1, void* arg2, void* arg3, void* arg4, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, int arg0, int arg1, void* arg2, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, int arg0, int arg1, short arg2, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, int arg0, void* arg1, void* arg2, void* arg3, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, void* arg0, short arg1, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, void* arg0, int arg1, int arg2, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, void* arg0, void* arg1, void* arg2, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, void* arg0, int arg1, void* arg2, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, void* arg0, void* arg1, int arg2, void* arg3, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, void* arg0, double arg1, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, void* arg0, void* arg1, int arg2, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, short arg0, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe short Callishort(void* thisObject, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, short arg0, void* arg1, void* arg2, void* arg3, void* arg4, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, System.Guid arg0, short arg1, void* arg2, int arg3, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, System.Guid arg0, short arg1, void* arg2, int arg3, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint46(void* thisObject, SharpDX.Result arg0, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe System.IntPtr CalliSystemIntPtr(void* thisObject, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, long arg0, void* arg1, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint49(void* thisObject, void* arg0, void* arg1, SharpDX.Mathematics.Interop.RawBool arg2, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, long arg0, void* arg1, void* arg2, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, void* arg0, int arg1, long arg2, long arg3, void* arg4, int arg5, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint52(void* thisObject, int arg0, void* arg1, SharpDX.Result arg2, void* arg3, void* methodPtr) { throw new NotImplementedException(); }
    //    public static unsafe int Calliint(void* thisObject, int arg0, long arg1, void* arg2, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, int arg0, float arg1, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, int arg0, System.Guid arg1, void* arg2, int arg3, void* arg4, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, void* arg0, void* arg1, int arg2, void* arg3, void* arg4, void* arg5, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, void* arg0, int arg1, void* arg2, void* arg3, void* arg4, void* arg5, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, void* arg0, void* arg1, int arg2, void* arg3, void* arg4, void* arg5, void* arg6, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, int arg0, void* arg1, int arg2, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint60(void* thisObject, SharpDX.Mathematics.Interop.RawBool arg0, long arg1, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, int arg0, void* arg1, int arg2, void* arg3, void* arg4, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint62(void* thisObject, int arg0, SharpDX.Mathematics.Interop.RawBool arg1, void* arg2, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint63(void* thisObject, SharpDX.Mathematics.Interop.RawBool arg0, float arg1, void* arg2, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, void* arg0, int arg1, long arg2, long arg3, void* arg4, int arg5, void* arg6, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, int arg0, int arg1, void* arg2, int arg3, void* arg4, void* arg5, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, int arg0, int arg1, void* arg2, int arg3, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, void* arg0, void* arg1, int arg2, void* arg3, void* arg4, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, void* arg0, int arg1, int arg2, void* arg3, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, long arg0, int arg1, void* arg2, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint70(void* thisObject, SharpDX.Mathematics.Interop.RawBool arg0, float arg1, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, void* arg0, int arg1, void* arg2, void* arg3, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, int arg0, long arg1, void* arg2, void* arg3, void* arg4, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint73(void* thisObject, SharpDX.Result arg0, int arg1, int arg2, long arg3, void* arg4, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, int arg0, long arg1, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, int arg0, long arg1, int arg2, void* arg3, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, System.Guid arg0, void* arg1, void* methodPtr) { throw new NotImplementedException(); }
      //  public static unsafe SharpDX.MediaFoundation.VideoFormat CalliSharpDXMediaFoundationVideoFormat(void* thisObject, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, System.Guid arg0, void* arg1, int arg2, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, int arg0, int arg1, void* arg2, void* arg3, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint80(void* thisObject, int arg0, void* arg1, SharpDX.Mathematics.Interop.RawBool arg2, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint81(void* thisObject, SharpDX.Result arg0, void* arg1, void* methodPtr) { throw new NotImplementedException(); }
      //.  public static unsafe SharpDX.Multimedia.WaveFormat CalliSharpDXMultimediaWaveFormat(void* thisObject, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, int arg0, void* arg1, int arg2, void* arg3, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, int arg0, void* arg1, int arg2, long arg3, long arg4, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, int arg0, void* arg1, long arg2, int arg3, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, void* arg7, void* arg8, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, void* arg0, void* arg1, int arg2, int arg3, void* arg4, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, void* arg0, void* arg1, void* arg2, void* arg3, int arg4, void* arg5, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, void* arg0, void* arg1, void* arg2, int arg3, void* arg4, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, int arg0, int arg1, int arg2, void* arg3, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, int arg0, System.Guid arg1, void* arg2, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, int arg0, System.Guid arg1, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, int arg0, float arg1, float arg2, void* arg3, void* arg4, void* methodPtr) { throw new NotImplementedException(); }
      //  public static unsafe int Calliint(void* thisObject, int arg0, void* arg1, void* arg2, void* arg3, void* arg4, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, System.Guid arg0, void* arg1, int arg2, void* arg3, void* arg4, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int Calliint(void* thisObject, System.Guid arg0, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, int arg0, int arg1, int arg2, int arg3, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7, void* methodPtr) { throw new NotImplementedException(); }
        public static unsafe int Calliint(void* thisObject, void* arg0, void* arg1, void* arg2, void* arg3, void* arg4, void* arg5, void* arg6, void* arg7, void* methodPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(void* arg0, void* arg1, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(void* arg0, void* arg1, void* arg2, void* arg3, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(void* arg0, void* arg1, void* arg2, void* arg3, void* arg4, void* arg5, void* funcPtr) { throw new NotImplementedException(); }
        public static unsafe int CalliFuncint104(void* arg0, SharpDX.Mathematics.Interop.RawBool arg1, int arg2, void* arg3, void* arg4, void* arg5, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(void* arg0, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(void* arg0, void* arg1, void* arg2, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(void* arg0, long arg1, void* arg2, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(int arg0, int arg1, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(System.Guid arg0, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(int arg0, int arg1, void* arg2, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(void* arg0, int arg1, int arg2, int arg3, long arg4, long arg5, long arg6, int arg7, void* arg8, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(long arg0, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(void* arg0, void* arg1, int arg2, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(System.Guid arg0, System.Guid arg1, void* arg2, int arg3, int arg4, void* arg5, int arg6, void* arg7, void* arg8, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(void* arg0, int arg1, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(void* arg0, void* arg1, void* arg2, int arg3, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(int arg0, void* arg1, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(System.Guid arg0, int arg1, void* arg2, void* arg3, void* arg4, void* arg5, void* arg6, void* funcPtr) { throw new NotImplementedException(); }
        public static unsafe SharpDX.Mathematics.Interop.RawBool CalliFuncSharpDXBool(void* arg0, void* arg1, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(void* arg0, int arg1, void* arg2, int arg3, int arg4, int arg5, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(void* arg0, void* arg1, void* arg2, int arg3, int arg4, void* arg5, int arg6, void* arg7, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(System.Guid arg0, void* arg1, void* arg2, void* arg3, void* arg4, void* arg5, void* arg6, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(int arg0, void* arg1, void* arg2, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(int arg0, int arg1, int arg2, void* arg3, void* arg4, void* arg5, void* arg6, void* funcPtr) { throw new NotImplementedException(); }
        public static unsafe SharpDX.Mathematics.Interop.RawBool CalliFuncSharpDXBool(int arg0, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(long arg0, void* arg1, void* arg2, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(int arg0, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(void* arg0, int arg1, int arg2, int arg3, int arg4, long arg5, int arg6, int arg7, int arg8, void* arg9, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(int arg0, int arg1, int arg2, void* arg3, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(void* arg0, int arg1, int arg2, int arg3, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(void* arg0, void* arg1, int arg2, void* arg3, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(void* arg0, int arg1, int arg2, void* arg3, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(void* arg0, int arg1, void* arg2, void* arg3, void* funcPtr) { throw new NotImplementedException(); }
        public static unsafe int CalliFuncint135(void* arg0, void* arg1, SharpDX.Mathematics.Interop.RawBool arg2, void* arg3, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(int arg0, void* arg1, int arg2, void* arg3, void* arg4, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(System.Guid arg0, void* arg1, void* arg2, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe void CalliFuncvoid(void* arg0, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe System.IntPtr CalliFuncSystemIntPtr(int arg0, int arg1, void* arg2, int arg3, int arg4, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(void* arg0, void* arg1, long arg2, void* arg3, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(System.Guid arg0, void* arg1, int arg2, void* funcPtr) { throw new NotImplementedException(); }
        public static unsafe int CalliFuncint142(int arg0, void* arg1, SharpDX.Result arg2, void* arg3, void* arg4, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe long CalliFunclong(long arg0, long arg1, long arg2, long arg3, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(int arg0, int arg1, int arg2, void* arg3, void* arg4, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(System.Guid arg0, int arg1, void* arg2, void* arg3, void* arg4, void* arg5, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(int arg0, void* arg1, void* arg2, void* arg3, void* funcPtr) { throw new NotImplementedException(); }
        public static unsafe int CalliFuncint147(void* arg0, int arg1, SharpDX.Mathematics.Interop.RawBool arg2, void* arg3, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(int arg0, long arg1, void* arg2, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(int arg0, int arg1, void* arg2, void* arg3, void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe long CalliFunclong(void* funcPtr) { throw new NotImplementedException(); }
        //public static unsafe int CalliFuncint(void* arg0, int arg1, void* arg2, void* funcPtr) { throw new NotImplementedException(); }
        public static unsafe int CalliFuncint(void* arg0, void* arg1, int arg2, void* arg3, void* arg4, void* funcPtr) { throw new NotImplementedException(); }
    }
}
#endif